### ISSUE TITLE
List Event - Lack of Documentation

### ISSUE THREAD

**Issue by jakadia** [pandosme/node-red-axis-camera#2]
I am curious how to use the List Events option on your node.  I think this is what I need because I am looking to get the statuses of my virtual inputs (tns1:Device/tnsaxis:IO/tnsaxis:VirtualInput).  Any help would be great!

**Comment by pandosme** [comment]
The List Event action is a way to ask the camera what events are avaialble.  It cannot be use to monitor a specific event.  There are a number of whay to get en event (from e.g. Digital I/O) into Node-RED to trigger a flow.  One way is described in  https://www.youtube.com/watch?v=KlWBsUG3JSI.
